version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/check_apache.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/health_check.sh
      timeout: 300
      runas: root

